version: '2'

networks:
    fabric:

services:

    orderer.dfarmadmin.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer.dfarmadmin.com
        environment:
            - ORDERER_HOST=orderer.dfarmadmin.com
        extra_hosts:
            - "peer0.dfarmadmin.com:3.133.93.116"
            - "peer0.dfarmretail.com:3.137.192.134"
            - "peer1.dfarmretail.com:3.137.192.134"
            - "peer2.dfarmretail.com:3.137.192.134"
        volumes:
            - ../crypto-config/ordererOrganizations/dfarmadmin.com/orderers/orderer.dfarmadmin.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/dfarmadmin.com/orderers/orderer.dfarmadmin.com/tls:/var/hyperledger/tls
            - ../channel-artifacts/:/var/hyperledger/configs
        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7050:7050
